#!/usr/bin/python
# Author: Jude Nelson

import json
import sys

def pretty_print(input):

    print json.dumps(input, sort_keys=False, indent=4, separators=(',', ': '))


for path in sys.argv[1:]:

    data = None

    try:
        with open(path, "r") as f:
            data_str = f.read()
            data = json.loads(data_str)

    except OSError, oe:
        print >> sys.stderr, "Failed to open %s: %s" % (path, oe.strerror)
        sys.exit(1)

    except Exception, e:
        print >> sys.stderr, "Failed to parse %s" % path
        sys.exit(1)

    try:
        if data is not None:
            pretty_print(data)

    except Exception, e:
        print >> sys.stderr, "Failed to parse %s" % (path)
        sys.exit(1)
