#!/bin/bash

if [ "$#" -ne 3 ]; then
    echo "Usage: combine_pdf <input1> <input2> <output>"
    exit 1
fi

INPUT1=$1
INPUT2=$2
OUTPUT=$3

gs -dBATCH -dNOPAUSE -q -sDEVICE=pdfwrite -sOutputFile=$OUTPUT $INPUT1 $INPUT2