#!/bin/bash
#change NEWSUBFOLDER below
#on OS X replace \t with <tab>

git filter-branch --index-filter \
  'git ls-files -s | sed "s-    \"*-&server/-" |
   GIT_INDEX_FILE=$GIT_INDEX_FILE.new \
   git update-index --index-info &&
   mv "$GIT_INDEX_FILE.new" "$GIT_INDEX_FILE"' HEAD