#!/bin/bash
#display the process(es) about to be killed and then actually kill them

PROCESS_NAME=$1

ps -A | grep $PROCESS_NAME | grep -v grep | grep -v kill_process | awk '{print "kill -9 " $1}'
ps -A | grep $PROCESS_NAME | grep -v grep | grep -v kill_process | awk '{print "kill -9 " $1}' | sh
